# Generated by Django 5.0.2 on 2024-03-01 21:24

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaCasosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RamoDireitoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagCasoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoConcretoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pergunta_caso', models.TextField()),
                ('resposta_caso', models.TextField()),
                ('fundamentacao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('meta_description', models.TextField(max_length=255)),
                ('keyword', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('old_url', models.SlugField(blank=True, null=True)),
                ('code', models.PositiveIntegerField(blank=True, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_casos.disciplinacasosmodel')),
                ('ramo_direito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_casos.ramodireitomodel')),
                ('tags', models.ManyToManyField(blank=True, to='app_casos.tagcasomodel')),
            ],
        ),
    ]
